// Printer-specific templates for project settings modifications
// Based on analysis of A1 printer original vs modified settings

import type { PrinterModel } from "../types/index.js";

/**
 * Printer template configuration
 */
export interface PrinterTemplate {
  /** Fields that need duplication from single to double values */
  duplicateFields: string[];
  /** Special handling for fields that need custom logic instead of simple duplication */
  specialFields: {
    [fieldName: string]: string;
  };
}

/**
 * Template configurations for different printer models
 */
export const printerTemplates: Record<Extract<PrinterModel, 'A1' | 'A1M'>, PrinterTemplate> = {
  A1: {
    // Fields that need duplication from single to double values for A1 (complete list from analysis)
    duplicateFields: [
      "activate_air_filtration",
      "additional_cooling_fan_speed",
      "chamber_temperatures",
      "circle_compensation_speed",
      "close_fan_the_first_x_layers",
      "complete_print_exhaust_fan_speed",
      "cool_plate_temp",
      "cool_plate_temp_initial_layer",
      "counter_coef_1",
      "counter_coef_2",
      "counter_coef_3",
      "counter_limit_max",
      "counter_limit_min",
      "default_filament_colour",
      "diameter_limit",
      "during_print_exhaust_fan_speed",
      "enable_overhang_bridge_fan",
      "enable_pressure_advance",
      "eng_plate_temp",
      "eng_plate_temp_initial_layer",
      "fan_cooling_layer_time",
      "fan_max_speed",
      "fan_min_speed",
      "filament_adaptive_volumetric_speed",
      "filament_adhesiveness_category",
      "filament_change_length",
      "filament_colour",
      "filament_cost",
      "filament_density",
      "filament_deretraction_speed",
      "filament_diameter",
      "filament_end_gcode",
      "filament_extruder_variant",
      "filament_flow_ratio",
      "filament_flush_temp",
      "filament_flush_volumetric_speed",
      "filament_ids",
      "filament_is_support",
      "filament_long_retractions_when_cut",
      "filament_map",
      "filament_max_volumetric_speed",
      "filament_minimal_purge_on_wipe_tower",
      "filament_multi_colour",
      "filament_pre_cooling_temperature",
      "filament_prime_volume",
      "filament_printable",
      "filament_ramming_travel_time",
      "filament_ramming_volumetric_speed",
      "filament_retract_before_wipe",
      "filament_retract_restart_extra",
      "filament_retract_when_changing_layer",
      "filament_retraction_distances_when_cut",
      "filament_retraction_length",
      "filament_retraction_minimum_travel",
      "filament_retraction_speed",
      "filament_scarf_gap",
      "filament_scarf_height",
      "filament_scarf_length",
      "filament_scarf_seam_type",
      "filament_self_index",
      "filament_settings_id",
      "filament_shrink",
      "filament_soluble",
      "filament_start_gcode",
      "filament_type",
      "filament_velocity_adaptation_factor",
      "filament_vendor",
      "filament_wipe",
      "filament_wipe_distance",
      "filament_z_hop",
      "filament_z_hop_types",
      "full_fan_speed_layer",
      "hole_coef_1",
      "hole_coef_2",
      "hole_coef_3",
      "hole_limit_max",
      "hole_limit_min",
      "hot_plate_temp",
      "hot_plate_temp_initial_layer",
      "impact_strength_z",
      "long_retractions_when_ec",
      "nozzle_temperature",
      "nozzle_temperature_initial_layer",
      "nozzle_temperature_range_high",
      "nozzle_temperature_range_low",
      "overhang_fan_speed",
      "overhang_fan_threshold",
      "overhang_threshold_participating_cooling",
      "pre_start_fan_time",
      "pressure_advance",
      "reduce_fan_stop_start_freq",
      "required_nozzle_HRC",
      "retraction_distances_when_ec",
      "slow_down_for_layer_cooling",
      "slow_down_layer_time",
      "slow_down_min_speed",
      "supertack_plate_temp",
      "supertack_plate_temp_initial_layer",
      "temperature_vitrification",
      "textured_plate_temp",
      "textured_plate_temp_initial_layer",
      "volumetric_speed_coefficients",
      "first_x_layer_fan_speed",
      "no_slow_down_for_cooling_on_outwalls"
    ],

    // Special handling for fields that need custom logic instead of simple duplication
    specialFields: {
      "filament_colour_type": "sequential" // 0, 1, 2, 3, ... instead of duplication
    }
  },

  A1M: {
    // A1M uses same duplication pattern as A1 (complete list from analysis)
    duplicateFields: [
      "activate_air_filtration",
      "additional_cooling_fan_speed",
      "chamber_temperatures",
      "circle_compensation_speed",
      "close_fan_the_first_x_layers",
      "complete_print_exhaust_fan_speed",
      "cool_plate_temp",
      "cool_plate_temp_initial_layer",
      "counter_coef_1",
      "counter_coef_2",
      "counter_coef_3",
      "counter_limit_max",
      "counter_limit_min",
      "default_filament_colour",
      "diameter_limit",
      "during_print_exhaust_fan_speed",
      "enable_overhang_bridge_fan",
      "enable_pressure_advance",
      "eng_plate_temp",
      "eng_plate_temp_initial_layer",
      "fan_cooling_layer_time",
      "fan_max_speed",
      "fan_min_speed",
      "filament_adaptive_volumetric_speed",
      "filament_adhesiveness_category",
      "filament_change_length",
      "filament_colour",
      "filament_cost",
      "filament_density",
      "filament_deretraction_speed",
      "filament_diameter",
      "filament_end_gcode",
      "filament_extruder_variant",
      "filament_flow_ratio",
      "filament_flush_temp",
      "filament_flush_volumetric_speed",
      "filament_ids",
      "filament_is_support",
      "filament_long_retractions_when_cut",
      "filament_map",
      "filament_max_volumetric_speed",
      "filament_minimal_purge_on_wipe_tower",
      "filament_multi_colour",
      "filament_pre_cooling_temperature",
      "filament_prime_volume",
      "filament_printable",
      "filament_ramming_travel_time",
      "filament_ramming_volumetric_speed",
      "filament_retract_before_wipe",
      "filament_retract_restart_extra",
      "filament_retract_when_changing_layer",
      "filament_retraction_distances_when_cut",
      "filament_retraction_length",
      "filament_retraction_minimum_travel",
      "filament_retraction_speed",
      "filament_scarf_gap",
      "filament_scarf_height",
      "filament_scarf_length",
      "filament_scarf_seam_type",
      "filament_self_index",
      "filament_settings_id",
      "filament_shrink",
      "filament_soluble",
      "filament_start_gcode",
      "filament_type",
      "filament_velocity_adaptation_factor",
      "filament_vendor",
      "filament_wipe",
      "filament_wipe_distance",
      "filament_z_hop",
      "filament_z_hop_types",
      "full_fan_speed_layer",
      "hole_coef_1",
      "hole_coef_2",
      "hole_coef_3",
      "hole_limit_max",
      "hole_limit_min",
      "hot_plate_temp",
      "hot_plate_temp_initial_layer",
      "impact_strength_z",
      "long_retractions_when_ec",
      "nozzle_temperature",
      "nozzle_temperature_initial_layer",
      "nozzle_temperature_range_high",
      "nozzle_temperature_range_low",
      "overhang_fan_speed",
      "overhang_fan_threshold",
      "overhang_threshold_participating_cooling",
      "pre_start_fan_time",
      "pressure_advance",
      "reduce_fan_stop_start_freq",
      "required_nozzle_HRC",
      "retraction_distances_when_ec",
      "slow_down_for_layer_cooling",
      "slow_down_layer_time",
      "slow_down_min_speed",
      "supertack_plate_temp",
      "supertack_plate_temp_initial_layer",
      "temperature_vitrification",
      "textured_plate_temp",
      "textured_plate_temp_initial_layer",
      "volumetric_speed_coefficients",
      "first_x_layer_fan_speed",
      "no_slow_down_for_cooling_on_outwalls"
    ],

    // Special handling for fields that need custom logic instead of simple duplication
    specialFields: {
      "filament_colour_type": "sequential" // 0, 1, 2, 3, ... instead of duplication
    }
  }
};
